; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32LixeeTft
framework = arduino
board_build.partitions = large_spiffs_16MB.csv
board_build.filesystem = littlefs
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
extends = env:esp32s3_ram_optimized
build_flags = 
	-Os
	-fno-rtti
	-Wdouble-promotion
	-Wall
	-Wextra
	-DARDUINO_ESP32S3_DEV
	-DCONFIG_ARDUHAL_LOG_COLORS=1
	-DARDUINO_RUNNING_CORE=1
	-DARDUINO_EVENT_RUNNING_CORE=1
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue

	-DCONFIG_LWIP_TCP_KEEPALIVE=1
	-DCONFIG_LWIP_TCP_KEEPIDLE=10000
	-DCONFIG_LWIP_TCP_KEEPINTVL=2000
	-DCONFIG_LWIP_TCP_KEEPCNT=3
	-DCONFIG_LWIP_SO_RCVTIMEO=1
	-DCONFIG_LWIP_SO_RCVBUF=1
	-DCONFIG_ARDUINO_EVENT_STACK_SIZE=8192
	
	
	
	-DCONFIG_BTDM_CONTROLLER_HCI_MODE_VHCI=y
	-DCONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST=y
	
	-DARDUINOJSON_USE_LONG_LONG=1
	-DARDUINOJSON_SLOT_ID_SIZE=2
	
	-DCONFIG_BT_LOG_LEVEL=0
	-DCONFIG_BTDM_LOG_LEVEL=0
lib_ldf_mode = deep+
lib_deps = 
	rlogiacco/CircularBuffer@^1.4.0
	bblanchon/ArduinoJson@^6.21.3
	paulstoffregen/Time@^1.6.1
	marvinroger/AsyncMqttClient@^0.9.0
	arkhipenko/TaskScheduler@^3.8.5
	https://github.com/ESP32Async/AsyncTCP.git#main
	https://github.com/ESP32Async/ESPAsyncWebServer.git#main
	

